-- Run this SQL in your Supabase Dashboard SQL Editor to fix permissions for BOTH tables.
-- 1. Setup 'contacts' table (if not exists)
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new',
    source TEXT DEFAULT 'contact_form',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- 2. Enable RLS
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
-- 3. Grant full permissions to service_role (Admin API)
GRANT ALL ON TABLE contacts TO service_role;
GRANT ALL ON TABLE leads TO service_role;
-- 4. Ensure service_role bypasses RLS (It should by default, but this enforces it)
ALTER ROLE service_role WITH BYPASSRLS;
-- 5. Diagnostics (Optional)
-- Check if the table exists and permissions are set.